- uses: actions/checkout@v3

- name: Setup Node
  uses: actions/setup-node@v3
  with:
    node-version: 18

- name: Setup pnpm
  run: npm install -g pnpm

- name: Install Dependencies
  run: pnpm install

- name: Build Project
  run: pnpm run build
